### ISSUE TITLE
Some fetches failed (xxxx) or were cancelled (x), caused by Some fetches failed (xxxx) or were cancelled (x)

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#313] opened 2017-07-03 11:15 UTC
hello 

i am trying to resolve this issue with a query
if this is from my cassandra config how can i get more info ?
if this is from my elasticsearch config how can i get more info ?
if this is from my heroic config how can i get more info ?

i don't know why "Some fetches failed "
is it cassandra fetch ? or elasticsearch fetch?

**Comment by udoprog** [comment] 2017-07-03 11:27
Hey, closing this since it's a duplicate of #243.

I will still need access to *complete logs* to help you. Make sure log4j2 is configured, and that you have enabled DEBUG for all Heroic logs. Then upload them to some place where they are accessible.

You can see how to do it here: https://github.com/spotify/heroic#logging

**Closed by udoprog** 2017-07-03 11:27 UTC
