### ISSUE TITLE
Clarification on Series

### ISSUE THREAD

**Issue by jcabmora** [spotify/heroic#60] opened 2016-07-20 21:17 UTC
Hello,
I am trying to understand how to organize our metrics, and I was wondering if you can provide a little bit more info in the Docs about series.  Specifically, what implications exist in terms of querying the data ( I am using the grafana heroic datasource plugin).
Also, when playing with the API I noticed an odd behavior:

First, add a series:

```
curl -s -X PUT -H "Content-Type: application/json" http://localhost:8080/metadata/series -d '{"key":"3175c2d7-3e93-4e30-9ca3-3bdf3b17baeb", "tags":{"meter":"cpu_util"}}' | python -m json.tool
{
    "errors": [],
    "times": [
        5920
    ]
}
```

Second, verify the series

```
curl -s -X POST -H "Content-Type: application/json" http://localhost:8080/metadata/series -d '{"key":"3175c2d7-3e93-4e30-9ca3-3bdf3b17baeb"}' | python -m json.tool
{
    "errors": [],
    "limited": false,
    "series": [
        {
            "key": "3175c2d7-3e93-4e30-9ca3-3bdf3b17baeb",
            "tags": {
                "meter": "cpu_util"
            }
        }
    ]
}
```

Third, delete the series, note deleted = 0

```
curl -s -X DELETE -H "Content-Type: application/json" http://localhost:8080/metadata/series -d '{"filter":["and", ["key","3175c2d7-3e93-4e30-9ca3-3bdf3b17baeb"],["=","meter","cpu_util"]]}' | python -m json.tool
{
    "deleted": 0,
    "errors": [],
    "failed": 0
}
```

Fourth, even though "deleted":0, it was actually deleted, which is evident if you query again

```
curl -s -X POST -H "Content-Type: application/json" http://localhost:8080/metadata/series -d '{"key":"3175c2d7-3e93-4e30-9ca3-3bdf3b17baeb"}' | python -m json.tool
{
    "errors": [],
    "limited": false,
    "series": []
}
```

However, you can't add the series back again:

```
curl -s -X PUT -H "Content-Type: application/json" http://localhost:8080/metadata/series -d '{"key":"3175c2d7-3e93-4e30-9ca3-3bdf3b17baeb", "tags":{"meter":"cpu_util"}}' | python -m json.tool
{
    "errors": [],
    "times": []
}
```

**Comment by udoprog** [comment] 2016-08-05 07:54
In another issue you mentioned that you are using the Elasticsearch 2.0 support, is this the case?

**Comment by dbrounst** [comment] 2016-08-05 15:08
The problem is the same in ES1.7.1 and ES2.2.1

**Comment by hexedpackets** [comment] 2019-03-21 20:13
Closing due to age, feel free to re-open if this is still an issue.

**Closed by hexedpackets** 2019-03-21 20:13 UTC
Labels: type:bug
