### ISSUE TITLE
Support promql remote read and write

### ISSUE THREAD

**Issue by huydx** [spotify/heroic#490] opened 2019-06-06 02:21 UTC
I think the current architecture of heroic able to support prometheus query (promql), we may just need some effort to 
- Support prometheus rpc (protobuf)
- Support nregex (negate regex) query (which is not natively supported by elasticsearch) (we may need full scan for this support)

How do you guys think about this issue, if possible I'm happy to help.

**Comment by hexedpackets** [comment] 2019-06-06 13:29
This is something we've been thinking about a bunch lately. Internally, we have a write-only adapter for Prometheus that we've started using in a few small places and @dmichel1 has been experimenting with adding read support.

I'm going to close this issue as a duplicate of #481, where we have some discussion going already.

**Closed by hexedpackets** 2019-06-06 13:29 UTC

**Comment by hexedpackets** [comment] 2019-06-06 13:33
Regarding the negative regex, the way that regex works right now is to do the comparison in [the API node](https://github.com/spotify/heroic/blob/master/heroic-component/src/main/java/com/spotify/heroic/filter/RegexFilter.java#L49) and not on Elasticsearch, so a negative regex filter could work the same way.

**Comment by dmichel1** [comment] 2019-06-06 13:37
We can opensource what we have so far if you would like to help contribute more to it. The write path goes through https://github.com/spotify/ffwd since we don't publish directory to heroic.

**Comment by huydx** [comment] 2019-06-11 13:34
Thanks for thoughtful reply, I will take a look at ffwd too. I think support remote read/write  effort should not be too hard and add a one more vertical scalable solution to a list of TSDB which support both remote read/write is a good thing for community too.
