### ISSUE TITLE
StackOverflowError when running write-performance 

### ISSUE THREAD

**Issue by jcabmora** [spotify/heroic#64] opened 2016-08-04 23:08 UTC
I am getting StackOverflowErrors when running the `write-performance` task.  

Steps to reproduce:
- Run Heroic with ShellServer enabled

```
port: 8080

shellServer:
    host: 192.168.42.2
    port: 9190

cluster:
  protocols:
    - type: nativerpc
      host: localhost
      port: 1394

  discovery:
    type: static
    nodes:
      - "nativerpc://127.0.0.1:1394"
...(other settings for suggest, metadata, metrics and consumer follow)
```

Running with Cassandra c2.1.13, ElasticSearch 2.2.1 (based on [PR 62](https://github.com/spotify/heroic/pull/62)), zookeeper 3.4.6 and Kafka 0.9.0.1  
- On another host, connect to the ShellServer:

```
java -cp "../target/*" com.spotify.heroic.HeroicShell --connect 192.168.42.2:9190
```
- set the timeout to something greater than default(10 seconds): 

```
heroic> timeout 60
Timeout updated to 60 seconds
```
- Run the `write-performance` task

```
heroic> write-performance --from=heroic --series=10 --target=100 --writes=200
Warmup step 1/4
..................................Command timed out (current timeout = 60s)
```

The following is the output captured in the heroic logs:

```
2016-08-04T22:52:05.0969: 22:52:05.092 [heroic-core-2] ERROR com.spotify.heroic.HeroicCore - Unhandled exception caught in core executor
2016-08-04T22:52:05.0971: java.lang.StackOverflowError
2016-08-04T22:52:05.0972: #011at java.util.Spliterators$IteratorSpliterator.<init>(Spliterators.java:1710)
2016-08-04T22:52:05.0973: #011at java.util.Spliterators.spliterator(Spliterators.java:420)
2016-08-04T22:52:05.0974: #011at java.util.Set.spliterator(Set.java:411)
2016-08-04T22:52:05.0976: #011at java.util.Collection.stream(Collection.java:581)
2016-08-04T22:52:05.0977: #011at com.spotify.heroic.common.SelectedGroup.stream(SelectedGroup.java:45)
2016-08-04T22:52:05.0978: #011at com.spotify.heroic.metric.LocalMetricManager$Group.map(LocalMetricManager.java:356)
2016-08-04T22:52:05.0979: #011at com.spotify.heroic.metric.LocalMetricManager$Group.write(LocalMetricManager.java:268)
2016-08-04T22:52:05.0980: #011at com.spotify.heroic.shell.task.WritePerformance.lambda$buildWrites$5(WritePerformance.java:249)
2016-08-04T22:52:05.0981: #011at eu.toolchain.async.DelayedCollectCoordinator.setupNext(DelayedCollectCoordinator.java:124)
2016-08-04T22:52:05.1024: #011at eu.toolchain.async.DelayedCollectCoordinator.checkNext(DelayedCollectCoordinator.java:115)
2016-08-04T22:52:05.1026: #011at eu.toolchain.async.DelayedCollectCoordinator.resolved(DelayedCollectCoordinator.java:60)
2016-08-04T22:52:05.1027: #011at eu.toolchain.async.DirectAsyncCaller.resolve(DirectAsyncCaller.java:10)
2016-08-04T22:52:05.1028: #011at eu.toolchain.async.immediate.ImmediateResolvedAsyncFuture.onDone(ImmediateResolvedAsyncFuture.java:59)
2016-08-04T22:52:05.1029: #011at eu.toolchain.async.DelayedCollectCoordinator.setupNext(DelayedCollectCoordinator.java:130)
2016-08-04T22:52:05.1031: #011at eu.toolchain.async.DelayedCollectCoordinator.checkNext(DelayedCollectCoordinator.java:115)
2016-08-04T22:52:05.1032: #011at eu.toolchain.async.DelayedCollectCoordinator.resolved(DelayedCollectCoordinator.java:60)
2016-08-04T22:52:05.1033: #011at eu.toolchain.async.DirectAsyncCaller.resolve(DirectAsyncCaller.java:10)
2016-08-04T22:52:05.1035: #011at eu.toolchain.async.immediate.ImmediateResolvedAsyncFuture.onDone(ImmediateResolvedAsyncFuture.java:59)
2016-08-04T22:52:05.1036: #011at eu.toolchain.async.DelayedCollectCoordinator.setupNext(DelayedCollectCoordinator.java:130)
2016-08-04T22:52:05.1037: #011at eu.toolchain.async.DelayedCollectCoordinator.checkNext(DelayedCollectCoordinator.java:115)
2016-08-04T22:52:05.1038: #011at eu.toolchain.async.DelayedCollectCoordinator.resolved(DelayedCollectCoordinator.java:60)
2016-08-04T22:52:05.1039: #011at eu.toolchain.async.DirectAsyncCaller.resolve(DirectAsyncCaller.java:10)
```

**Comment by udoprog** [comment] 2016-08-05 07:57
This is caused by immediate futures being chained together when collecting data to be used for the performance tests. These cause subsequent steps to be called on the same stack.

I would look into decoupling the firing of callbacks for immediate futures a bit to mitigate this.

**Comment by hexedpackets** [comment] 2019-03-21 20:14
Closing due to age, feel free to re-open if this is still an issue.

**Closed by hexedpackets** 2019-03-21 20:14 UTC
Labels: type:bug
