### ISSUE TITLE
just compiled in master none query metrics works

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#243] opened 2017-03-23 09:16 UTC
Hello,

I just wanted to update the source code from master 
everithing in the compilation goes right
no errors
i can write data 
elasticsearch is ok
i can count the number of series

BUT i still get this error on all my different queries
```
Some fetches failed (628) or were cancelled (0), caused by Some fetches failed (628) or were cancelled (0)
```

wich source code do i compile to get things work ?

**Comment by valentinul** [comment] 2017-03-23 10:14
Hi, 

I've had the same issue when running @latest ... 

I've ended up using @be6c06f

**Comment by udoprog** [comment] 2017-03-23 11:43
Hey,

As per previous tests, with the versions of C* that @valentinul was using it seemed to work fine with a fresh cluster. So I'd need one of you to do some testing with your existing clusters.

Please do one of the following:

**1)**
The current gRPC implementation could potentially mask the root cause of the issue, you could try running the following branch:
https://github.com/udoprog/heroic/tree/grpc-log-errors

This patch just adds more logging on top of the existing master:
https://github.com/spotify/heroic/compare/master...udoprog:grpc-log-errors?expand=1

**2)**
Alternatively, run heroic-shell with your configuration _after_ you've removed the **cluster** section.
This causes Heroic to talk to itself locally, which should hopefully propagate any errors raised.

```bash
$> mvn clean package -D maven.test.skip=true
$> tools/heroic-shell -C <config>
heroic> query count by host
```

Doing this should hopefully provoke the error you are seeing, and should give us a complete stack trace to work with.

**Comment by valentinul** [comment] 2017-03-24 10:31
Hi John,

Maybe I can test it later. I'll let you know.

all the best,
valentin

**Comment by lucilecoutouly** [comment] 2017-04-07 10:20
hello 

i retry with a clean intall and i have the same error
`"Some fetches failed (1) or were cancelled (0), caused by Some fetches failed (1) or were cancelled (0)"`

**Comment by udoprog** [comment] 2017-04-07 10:47
@lucilecoutouly right, but what (if anything) do you see in the logs?

**Comment by lucilecoutouly** [comment] 2017-04-07 11:03
when i did this
```

 tools/heroic-shell -C <config>
heroic> query count by host
```
i get no error
this query works

**Comment by lucilecoutouly** [comment] 2017-04-07 11:17
```
/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-cp", "heroic-dist/target/heroic-dist-0.0.1-SNAPSHOT-shaded.jar"]

CMD ["com.spotify.heroic.HeroicService","config/heroic.yml"]
```

**Comment by lucilecoutouly** [comment] 2017-04-27 09:20
` [elasticsearch[Aunt May Parker][generic][T#1]] INFO  org.elasticsearch.client.transport - [Aunt May Parker] failed to get node info for [#transport#-1][heroic-nsadb-read][inet[elasticsearch-master/10.42.192.2:9300]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[elasticsearch-master/10.42.192.2:9300]][cluster:monitor/nodes/info] request_id [4] timed out after [5000ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
09:20:15.130 [elasticsearch[Air-Walker][generic][T#1]] INFO  org.elasticsearch.client.transport - [Air-Walker] failed to get node info for [#transport#-1][heroic-nsadb-read][inet[elasticsearch-master/10.42.192.2:9300]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[elasticsearch-master/10.42.192.2:9300]][cluster:monitor/nodes/info] request_id [52] timed out after [5000ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
09:20:25.142 [elasticsearch[Air-Walker][generic][T#1]] INFO  org.elasticsearch.client.transport - [Air-Walker] failed to get node info for [#transport#-1][heroic-nsadb-read][inet[elasticsearch-master/10.42.192.2:9300]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[elasticsearch-master/10.42.192.2:9300]][cluster:monitor/nodes/info] request_id [53] timed out after [5000ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
09:20:25.142 [elasticsearch[Aunt May Parker][generic][T#1]] INFO  org.elasticsearch.client.transport - [Aunt May Parker] failed to get node info for [#transport#-1][heroic-nsadb-read][inet[elasticsearch-master/10.42.192.2:9300]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[elasticsearch-master/10.42.192.2:9300]][cluster:monitor/nodes/info] request_id [5] timed out after [5000ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by lucilecoutouly** [comment] 2017-04-28 07:51
heroic> query count by host
Command timed out (current timeout = 10s)
time: 10.240 s
heroic> timeout 300
Timeout updated to 300 seconds
heroic> query count by host
ERR: ShardError(nodes=[grpc://heroic-read:1394#query, grpc://heroic-write:1394#q
uery], shard={site=nsadb}, error=Request finished with status code (Status{code=
UNKNOWN, description=null, cause=null}), caused by Request finished with status
code (Status{code=UNKNOWN, description=null, cause=null}))
LIMITS: []
TRACE:
com.spotify.heroic.CoreQueryManager#query (in 50.088ms)
  NO TRACE
time: 50.094 s

**Comment by lucilecoutouly** [comment] 2017-04-28 07:54
query count by host
ERR: ShardError(nodes=[[local]#query], shard={}, error=Some fetches failed (1103
48) or were cancelled (0), caused by Some fetches failed (110348) or were cancel
led (0))
LIMITS: []
TRACE:
com.spotify.heroic.CoreQueryManager#query (in 5.016ms)
  NO TRACE
time: 5.273 s

**Comment by udoprog** [comment] 2017-04-28 10:44
Hey @lucilecoutouly, we will still need complete logs for the nodes in use.

**Comment by lucilecoutouly** [comment] 2017-05-16 09:25
tell me exactly what to test because i still have this issue when i try heroic master

**Comment by lucilecoutouly** [comment] 2017-06-08 09:20
hello,
I do a fresh  cluster and i still can't query metrics:
```
POST /query/metrics HTTP/1.1
Host: her-rsdb:80
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: a67ffad2-b12e-1b43-36db-22104c95b51c

{ "source": "points", "range": {"type": "absolute", "start": 1388559240000, "end": 1388613900000}, "filter": ["and", ["key", "nrh"]]}
```

and the answer
```
{
    "queryId": "479f0a04-c7c4-43fe-89ca-ce5ce255768a",
    "range": {
        "start": 1388559240000,
        "end": 1388613900000
    },
    "trace": {
        "what": {
            "name": "com.spotify.heroic.CoreQueryManager#query"
        },
        "elapsed": 232368,
        "children": [
            {
                "what": {
                    "name": "com.spotify.heroic.CoreQueryManager#query_shard[{role=test}]"
                },
                "elapsed": 232994,
                "children": [
                    {
                        "what": {
                            "name": "[local]#query"
                        },
                        "elapsed": 232287,
                        "children": [
                            {
                                "what": {
                                    "name": "com.spotify.heroic.metric.LocalMetricManager#query"
                                },
                                "elapsed": 232491,
                                "children": []
                            }
                        ]
                    }
                ]
            }
        ]
    },
    "limits": [
        "AGGREGATION"
    ],
    "commonTags": {},
    "result": [],
    "preAggregationSampleSize": 0,
    "errors": [
        {
            "type": "query",
            "error": "Some fetches failed (100) or were cancelled (24)"
        }
    ]
}

```

**Comment by lucilecoutouly** [comment] 2017-07-03 13:48
here is an error i get : 
```
2017-07-03 13:44:05,531 DEBUG c.d.d.c.RequestHandler [heroic-core-6] [1145274429-1] Error querying /10.42.175.186:9042 : com.datastax.driver.core.exceptions.BusyPoolException: [/10.42.175.186] Pool is busy (no available connection and the queue has reached its max size 256) 
```

how to configure cassandra ?

**Comment by hexedpackets** [comment] 2019-03-21 20:42
Closing due to age, feel free to re-open if this is still an issue.

**Closed by hexedpackets** 2019-03-21 20:42 UTC
Labels: type:bug
